# For more information see: https://help.github.com/actions/language-and-framework-guides

---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_BACKTRACE: full

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          rustup update --no-self-update stable
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-hack --debug
      - name: Run
        run: make lint
        continue-on-error: false
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          rustup update --no-self-update stable
          sudo apt-get update
          sudo apt-get install -y inxi
      - name: Run
        run: make test
        continue-on-error: false
